# Site settings
email: ktagilbert@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ktgilbert.com/" # the base hostname & protocol for your site
twitter_username: Kt_a_Gilbert
github_username:  ktagilbert
time: "2015-07-15 19:50:33 -0700"
page_path: /title/category/
permalink: /blog/:title
comments: true
paginate: 9
paginate_path: "/blog/page:num/"
digest: true
markdown: kramdown

# Heroku Config
gems: ['kramdown', 'jekyll-assets']

exclude: ['vendor', 'Procfile', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'config.ru']
