# Site settings
title: Rookie Dev
email: ktagilbert@gmail.com 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.rookie-dev.com" # the base hostname & protocol for your site
twitter_username: Kt_a_Gilbert
github_username:  ktagilbert
time: "2015-07-15 19:50:33 -0700"

# Build settings
markdown: kramdown

# Heroku Config
gems: ['kramdown']
exclude: ['vendor', 'Procfile', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'config.ru']