# Site settings
title: Rookie Dev
email: ktagilbert@gmail.com
description: A site I made to help me learn about web development. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Kt_a_Gilbert
github_username:  ktagilbert

# Build settings
markdown: kramdown
