# Site settings
title: Rookie Dev
email: ktagilbert@gmail.com 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: Kt_a_Gilbert
github_username:  ktagilbert

# Build settings
markdown: kramdown
